### ISSUE TITLE
Potential Confusion of Brand

### ISSUE THREAD

**Issue by Lvl4Sword** [ruuvi/ruuvi_brand#2]
The Ruuvi image looks a lot like TinyChat's.
TinyChat:
https://pbs.twimg.com/profile_images/793463625813942273/-qFcqzLn_400x400.jpg
Ruuvi:
https://avatars3.githubusercontent.com/u/12087190

**Comment by laurijamsa** [comment]
A bit, but definitely not too much. Thanks for the heads up anyways.
